name: Call Reusable Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        default: stageing
        options:
          - dev
          - staging
          - production
      Region:
        description: 'Enter your region'
        required: true          

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: ${{ inputs.environment }}
